name: hashmap
version: 0.0.1
description: Call Rust from Dart

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^7.2.10

ffigen:
  output: 'hashmap_bindings.dart'
  headers:
    entry-points:
      - 'hashmap.h'

environment:
  sdk: '>=2.18.0 <3.0.0'
