# visit https://github.com/eqrion/cbindgen/blob/master/template.toml
# for the template toml file for cbindgen

language = "C"

# header guard
include_guard = "_HASHMAP_RUST_"
pragma_once = true

[export]
# Add structs here to export them, cbindgen doesn't export structs by default somehow
include = [
    "Foo",
    "Bar"
]
